integration/oqs_openssl/run.sh
=> Option to specify branches

README.md
Added Windows dependencies, and myself as a contributor.
=> Added Windows dependencies.

README.md, integration/run_all_ubuntu.sh
This script performs the setup/install steps in the docs for OpenSSH and OpenSSL components, then runs both tests.
=> Added run all script for Ubuntu systems

integration/oqs_openssh/run.sh
=> Add OpenSSH test case to build without OpenSSL

integration/oqs_openssl/run.sh
=> Modify OpenSSL tests to use root-issued CA certs

.circleci/config.yml, integration/oqs_openssh/run_all.sh, integration/oqs_openssh/scripts/build_openssh.sh, integration/oqs_openssh/scripts/clone_openssh.sh, integration/oqs_openssh/tests/test_openssh.py
This PR adds openssh hybrid auth test cases.
(NEED TO TRY IT FIRST BEFORE MERGING)
=> Added hybrid auth openssh test cases.

.circleci/config.yml
This PR would trigger building and pushing to docker hub of the ci images, removing the need for manual build-and-push.
=> Image build automation

alpine/Dockerfile, centos-7/Dockerfile, centos-8/Dockerfile, debian-buster/Dockerfile, ubuntu-bionic/Dockerfile
@xvzcf Anything (else) missing? If so, please update #41
=> implement #41

.circleci/config.yml, debian-buster/Dockerfile
Debian support for ARM x-building (supporting https://github.com/open-quantum-safe/liboqs/pull/964)
=> ARM crossbuild

.circleci/config.yml
=> Adding ARM64 CI image

ubuntu-focal/Dockerfile
=> upgrading doxygen to 1.9.1

ubuntu-focal/Dockerfile
As per https://github.com/open-quantum-safe/liboqs/pull/1030#issuecomment-876480446
=> adding yamllint

.circleci/config.yml, debian-bullseye/Dockerfile
Prerequisite for https://github.com/open-quantum-safe/profiling/pull/69
=> upgrading to Debian 11/bullseye

.circleci/config.yml, ubuntu-focal/Dockerfile
Enabling https://github.com/open-quantum-safe/liboqs/issues/1239
=> Adding scan-build support

ubuntu-focal/Dockerfile
Update required as per https://github.com/open-quantum-safe/liboqs/pull/1240#issuecomment-1169948263
=> upgrade to llvm14

ubuntu-focal/Dockerfile
Alternative fix for https://github.com/open-quantum-safe/liboqs/issues/1332
=> revert to doxygen 1.9.2

.circleci/config.yml, ubuntu-jammy/Dockerfile
Baseline for fixing https://github.com/open-quantum-safe/liboqs/issues/1340
=> adding Ubuntu Jammy/22

.circleci/config.yml, ubuntu-focal/Dockerfile, ubuntu-jammy/Dockerfile
Also simplified building ARM64 CI image
=> adding pip3 to enable copy_from_upstream test

ubuntu-focal/Dockerfile
Fixes [latest liboqs CI failure](https://app.circleci.com/pipelines/github/open-quantum-safe/liboqs/2990/workflows/e9d97ab3-27ab-4701-b779-ed943e0d6d5d/jobs/23912).
=> Add doxygen to ubuntu-focal for x86_64

ubuntu-focal/Dockerfile
=> set env vars GOROOT and PATH explicitly

.circleci/config.yml, README.md, ubuntu-latest/Dockerfile
Builds on Ubuntu Jammy instructions ensuring components are available for all OQS sub projects.
=> Adding Ubuntu latest

.github/workflows/build.yml, .github/workflows/push.yml
See related PRs https://github.com/open-quantum-safe/liboqs/pull/2050 and https://github.com/open-quantum-safe/oqs-demos/pull/343.
=> Update to public GitHub Arm runner
