open-quantum-safe/ci-containers

integration/oqs_openssh/README.md, integration/oqs_openssl/README.md
Added cmds to readme to make it easier to collect run.sh output for later inclusion in the test results wiki. Some VMs don't have a shared clipboard which makes collecting results fiddly and error prone.
=> Add example tee commands to READMEs to capture run.sh output.

integration/oqs_openssh/README.md, integration/oqs_openssh/run.sh, integration/oqs_openssl/README.md, integration/oqs_openssl/run.sh
@smashra, commits dd417002a89b2c98190a541494551fd0a9bfc119 and 72f7cfa63f6bc300452ecd6ac96715384b490800 broke the integration tests for me on macOS 10.14 and various Ubuntus.  I tried for several hours to get them working, but to no avail.  I've reverted to prior versions which do work.  
At this point in time, the integration tests reflect an automated version of what the README.md's instructions are -- and nothing more.  The README.md instructions don't build shared libraries, and so I'm fine with the integration tests not doing it.
If you're able to get them working again and they work reliably on all our target platforms, then we can re-add them.
=> Revert shared library changes

integration/oqs_openssl/winrun.ps1
Fixed typo in powershell script, correcting version check (1.0.2 vs 1.1.1)
=> Fixed 1.0.2-vs-1.1.1 typo in powershell script

.travis.yml, README.md
Added basic travis CI config to test:
* Ubuntu Xenial & Trusty (with default GCC versions)
* Mac OS with clang
ccache has been enabled to try to speed up the build too.
=> Enable basic Travis configuration

integration/oqs_openssl/tests/test_openssl.py
Removed round1 candidates that didn't make it to round2 (bigquake, lima, titanium) in OpenSSL V1.1.1 tests. Depends on OpenSSL's [PR82](https://github.com/open-quantum-safe/openssl/pull/82).
=> Only keep round2 candidates in OpenSSLv1.1.1

centos-7/Dockerfile, centos-7/build-openssl111d.sh, centos-8/Dockerfile, debian-buster/Dockerfile, ubuntu-bionic/Dockerfile
Enabled all (remaining) images to run docker. If OK, please also push resultant images to `openquantumsafe` (dockerhub).
I'll follow up with a PR for an automated CircleCI image-test-build-push config in `oqs-demos` using these images. For the final auto-push to work seamlessly, please [install a CircleCI context](https://circleci.com/docs/2.0/contexts/) `openquantumsafe` with `DOCKER_LOGIN` and `DOCKER_PASSWORD` environment variables correctly set.
=> docker added

ubuntu-bionic/Dockerfile
Turns out some Go scripts in BoringSSL require a more recent version of Go than what's available through the Ubuntu 18.04 packages.
=> Modified ubuntu-bionic Dockerfile to obtain latest Go version.

.circleci/config.yml
Apologies @dstebila for cluttering your personal docker hub namespace with ci-images in [the previous run](https://app.circleci.com/pipelines/github/open-quantum-safe/ci-containers/43/workflows/b40cb6e2-3015-4701-b08f-76d8b3dd559c/jobs/601): This PR fixes this.
=> correcting image target location

centos-8/Dockerfile
clang support not a bad idea anyway. Test run [here](https://app.circleci.com/pipelines/github/baentsch/testing/59/workflows/34c1ba29-32c9-44cd-98d2-33ef1bc3d821/jobs/158)
Reason behind this: New upstream Dilithium self- (and KAT) tests fail only on Centos-8 when building with `-DOQS_PORTABLE_BUILD=OFF` using (Centos-)gcc but pass with the same cmake-setting using `clang`... 
gcc generates code that runs OK with `-DOQS_PORTABLE_BUILD=ON`. Did we ever encounter sth like this before, @xvzcf ? Should I create an issue rather than setting CC=clang in CI for Centos-8 to ensure we get to the bottom of this?
=> adding clang to Centos-8

ubuntu-bionic/Dockerfile
In support of https://github.com/open-quantum-safe/liboqs/pull/881
=> adding valgrind 3.16.1 to ubuntu-bionic

.circleci/config.yml, ubuntu-bionic/Dockerfile, ubuntu-focal/Dockerfile
As ubuntu is not supporting i386 for focal this PR is to manually insert more current `cmake` into the bionic image. Should allow https://github.com/open-quantum-safe/liboqs/pull/1161 to pass.
=> upgrade bionic cmake

ubuntu-focal/Dockerfile
Preparing for resolution of https://github.com/open-quantum-safe/liboqs/issues/167.
Problem: ARM64 image times out building (a required recent) doxygen. Vote on proposals / Suggestions welcome how to resolve: 
1) Drop doxygen from ARM64 CI image
2) Utilize larger ARM64 machine (currently: [large](https://github.com/open-quantum-safe/ci-containers/blob/27a2bcfa1d376fd937382c0996d0733f636e5255/.circleci/config.yml#L62) -- see https://circleci.com/product/features/resource-classes/
I'll add code for option "1" without votes to the opposite.
=> enable profiling analysis

ubuntu-focal/Dockerfile
Adds ci-dependencies for https://github.com/open-quantum-safe/liboqs/pull/1337
=> ubuntu-focal: add python3-git, python3-wget, npm and ajv dependencies

.circleci/config.yml, ubuntu-focal/Dockerfile
Fixing failed CI run https://github.com/open-quantum-safe/ci-containers/runs/10530412595:
- clang14 install files no longer available for ubuntu focal ARM image -> update to clang-15
- Fixes to docker tag & push commands
=> update to clang15 and docker command fixes

ubuntu-focal/Dockerfile, ubuntu-jammy/Dockerfile
Enables full src+doc gen via `generate.py` scripts.
Also optimizes `go` installation for ubuntu22.
=> python package update for docgen

debian-buster/Dockerfile
This would be a quick fix for `armhf` testing: Upgrade `cmake` to a more recent version. Quick fix only as this [OS is pretty dated not receiving security patches any more](https://www.debian.org/releases/buster/) and finally going EOL in 7 months. My strong preference is to upgrade this if we want to keep supporting this. But then again:
Judging from the lack of feedback in https://github.com/orgs/open-quantum-safe/discussions/1583 it doesn't really seem to matter to anyone what platforms we support or in which way.
So I put an alternative fix for [the cmake induced CI failure](https://github.com/open-quantum-safe/liboqs/actions/runs/6756402858/job/18365865360?pr=1601) into https://github.com/open-quantum-safe/liboqs/pull/1601/commits/af759bbf743bb3ecc2e7315cf10c1785e93bcc05 : Just …
=> Update cmake in debian buster

ubuntu-focal/Dockerfile
To enable CI testing of cross-building for Windows.
See also: open-quantum-safe/liboqs#1696
=> Install MinGW in Focal for cross-compilation

ubuntu-focal/Dockerfile
This PR adds `sudo` and `curl` to the Ubuntu focal image which is used in liboqs CI. 
[open-quantum-safe/liboqs#1745](https://github.com/open-quantum-safe/liboqs/pull/1745) adds support for pulling formally verified code from libjade into liboqs. Building libjade requires nix, which in turn requires `curl` and `sudo` currently missing from this image.
=> Add curl and sudo to ubuntu-focal

ubuntu-focal/Dockerfile
Related to https://github.com/open-quantum-safe/boringssl/pull/115
A better way is to create an image for ubuntu noble...
=> update go to 1.22.2

ubuntu-focal/Dockerfile
Fix the error
`go: cannot find GOROOT directory: 'go' binary is trimmed and GOROOT is not set`
by setting `GOROOT`
=> Update Go to 1.22.3 and fix errors

ubuntu-latest/Dockerfile
As a follow-up to #85 and to enable https://github.com/open-quantum-safe/liboqs/pull/1909, install additional dependencies to enable `scan-build` and Windows cross-compilation on Ubuntu Noble.
=> Install scan-build and gcc cross-compilation dependencies

ubuntu-latest/Dockerfile
Baking `actionlint` in as per discussion here: https://github.com/open-quantum-safe/liboqs/pull/1880/commits/267c95ea3713c931c9511aadd0ee7361a9236156#r1725498088
=> Bake actionlint v1.7.1 from source for GitHub workflow validation

ubuntu-latest/Dockerfile
If `actionlint` is built as per #87, `git` / `python3` are not available for the rest of the in-progress basic.yml tests.
This re-ordering corrects that.
=> Fix build order

ubuntu-latest/Dockerfile
This installs NVCC on ubuntu-latest to run cuPQC build tests.
=> Install NVCC on ubuntu-latest to run cuPQC build tests

ubuntu-latest/Dockerfile
Update the ubuntu-latest image to use OpenJDK 21 and set the `JAVA_HOME` env variable to support `liboqs-java`.
See https://github.com/open-quantum-safe/liboqs-java/pull/32 for a POC which installs the apt package and sets the env variable within a workflow.
=> Update OpenJDK version

ubuntu-latest/Dockerfile
This allows actionlint to recognize the new `macos-15`, `windows-2025`, and `ubuntu-24.04-arm` runners.
=> Bump actionlint to v1.7.7
